#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.{build}

# branches to build
branches:
  only:
    - main

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea)
#skip_tags: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
  - Ubuntu
  - Visual Studio 2019

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - curl -sSL https://dot.net/v1/dotnet-install.sh | sudo bash /dev/stdin --channel 5.0 --version 5.0.100 --install-dir /usr/share/dotnet

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
    project: Juukbe.Common.sln
    verbosity: minimal
    
# scripts to run before build
before_build:
  - dotnet --info
  - cmd: nuget restore Juukbe.Common.sln

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# TODO

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# TODO

#---------------------------------#
#        global handlers          #
#---------------------------------#

# TODO

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  # Email
  - provider: Email
    to:
      - juukbe@protonmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
