#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 0.0.{build}

branches:
  only:
    - main

skip_tags: true

max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
  - Ubuntu
  - Visual Studio 2019

install:
  - cmd: >-
      choco install dotnet-sdk --version 5.0.100

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build:
    project: Juukbe.Common.sln
    verbosity: minimal

build_script:
  - cmd: dotnet build Juukbe.Common.csproj -c Release /p:CI=true /p:GeneratePackageOnBuild=false
  - cmd: dotnet test Juukbe.Common.csproj -c Release /p:CI=true
  - cmd: dotnet pack Juukbe.Common.csproj --no-build -c Release /p:Packing=true /p:PackageOutputPath=%CD%\.nupkgs /p:CI=true

before_build:
  - dotnet --info
  - cmd: nuget restore Juukbe.Common.sln

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  # Email
  - provider: Email
    to:
      - juukbe@protonmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
